package org.mastercode.datastructurealgoritms.stub;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import java.net.URL;

/**
 * This class was generated by Apache CXF 3.4.2
 * 2024-10-21T17:06:01.252+04:00
 * Generated source version: 3.4.2
 *
 */
@WebServiceClient(name = "test_asb_plastik_card_services",
                  wsdlLocation = "classpath:wsdl/AsbPlastikCardServices.wsdl",
                  targetNamespace = "http://fortunawsc.isube.asb.com/")
public class TestAsbPlastikCardServices extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://fortunawsc.isube.asb.com/", "test_asb_plastik_card_services");
    public final static QName TestAsbPlastikCardServicesSoap = new QName("http://fortunawsc.isube.asb.com/", "test_asb_plastik_card_servicesSoap");
    public final static QName TestAsbPlastikCardServicesSoap12 = new QName("http://fortunawsc.isube.asb.com/", "test_asb_plastik_card_servicesSoap12");
    static {
        URL url = TestAsbPlastikCardServices.class.getClassLoader().getResource("wsdl/AsbPlastikCardServices.wsdl");
        if (url == null) {
            java.util.logging.Logger.getLogger(TestAsbPlastikCardServices.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "classpath:wsdl/AsbPlastikCardServices.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public TestAsbPlastikCardServices(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public TestAsbPlastikCardServices(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TestAsbPlastikCardServices() {
        super(WSDL_LOCATION, SERVICE);
    }

    public TestAsbPlastikCardServices(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public TestAsbPlastikCardServices(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public TestAsbPlastikCardServices(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns TestAsbPlastikCardServicesSoap
     */
    @WebEndpoint(name = "test_asb_plastik_card_servicesSoap")
    public TestAsbPlastikCardServicesSoap getTestAsbPlastikCardServicesSoap() {
        return super.getPort(TestAsbPlastikCardServicesSoap, TestAsbPlastikCardServicesSoap.class);
    }

    /**
     *
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TestAsbPlastikCardServicesSoap
     */
    @WebEndpoint(name = "test_asb_plastik_card_servicesSoap")
    public TestAsbPlastikCardServicesSoap getTestAsbPlastikCardServicesSoap(WebServiceFeature... features) {
        return super.getPort(TestAsbPlastikCardServicesSoap, TestAsbPlastikCardServicesSoap.class, features);
    }


    /**
     *
     * @return
     *     returns TestAsbPlastikCardServicesSoap
     */
    @WebEndpoint(name = "test_asb_plastik_card_servicesSoap12")
    public TestAsbPlastikCardServicesSoap getTestAsbPlastikCardServicesSoap12() {
        return super.getPort(TestAsbPlastikCardServicesSoap12, TestAsbPlastikCardServicesSoap.class);
    }

    /**
     *
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TestAsbPlastikCardServicesSoap
     */
    @WebEndpoint(name = "test_asb_plastik_card_servicesSoap12")
    public TestAsbPlastikCardServicesSoap getTestAsbPlastikCardServicesSoap12(WebServiceFeature... features) {
        return super.getPort(TestAsbPlastikCardServicesSoap12, TestAsbPlastikCardServicesSoap.class, features);
    }

}
